Repository boostcampwm2023/web02-fancamp, pull requests merged in 2023-12, with the labels that each got.

#65 Feat fe/reusable components
  frontend/src/components/slider/ImageSlider.tsx
  frontend/src/components/slider/MediaSlider.tsx
  frontend/src/hooks/useInfiniteSlider.ts
  frontend/src/pages/camps/post/PostModalLogic.tsx
  frontend/src/pages/camps/post/PostModalTemplate.tsx
  frontend/src/pages/feed/FeedCardLogic.tsx
  frontend/src/pages/feed/FeedCardTemplate.tsx
  frontend/src/pages/feed/FeedPage.tsx
  frontend/src/type/api/post.d.ts
  frontend/src/utils/file.ts
Labels: 🌝 FE, ✨ feature, 🐞 fix

#66 [BE] 회원가입 시 중복 여부 검사
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/http/auth.http
Labels: 🌚 BE, ✨ feature

#69 [BE] api 수정 및 추가
  backend/src/auth/auth.controller.ts
  backend/src/camp/camp.controller.ts
  backend/src/camp/camp.service.ts
  backend/src/camp/entities/subscription.entity.ts
  backend/src/camp/subscription.repository.ts
  backend/src/camp/subscription.service.ts
  backend/src/http/auth.http
  backend/src/http/camp.http
  backend/src/http/like.http
  backend/src/http/post.http
  backend/src/post/post.controller.ts
  backend/src/post/post.module.ts
  backend/src/post/post.service.ts
  backend/src/utils/constants.ts
Labels: 🌚 BE, ✨ feature

#68 fix-fe: 채팅 인피니트 스크롤 버그 임시 해결, useMemo 적용
  frontend/src/components/chat/ChatBoxBody.tsx
  frontend/src/hooks/useIntersectionObserver.ts
Labels: 🌝 FE, 🐞 fix

#73 [BE] 소켓으로 업데이트 추가, 포스트 썸네일 응답 수정
  backend/src/app.module.ts
  backend/src/camp/camp.controller.ts
  backend/src/camp/camp.repository.ts
  backend/src/camp/camp.service.ts
  backend/src/camp/entities/camp.entity.ts
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.repository.ts
  backend/src/image/image.service.ts
  backend/src/post/comment.gateway.ts
  backend/src/post/post.gateway.ts
  backend/src/post/post.module.ts
  backend/src/post/post.service.ts
  backend/src/utils/logger.middleware.ts
  backend/src/utils/sentiment.ts
Labels: 🌚 BE, ✨ feature, 🐞 fix

#71 [FE] 구독 리스트 Context 구현, SideMenu에 표시, 알림 기능
  frontend/index.html
  frontend/src/API/socket.ts
  frontend/src/components/chat/ChatBox.tsx
  frontend/src/components/chat/ChatBoxBody.tsx
  frontend/src/components/chat/ChatBoxInputBar.tsx
  frontend/src/components/chat/ChatBoxMessage.tsx
  frontend/src/components/menu/SideMenu.tsx
  frontend/src/constants/camp.ts
  frontend/src/constants/localStorageKeys.ts
  frontend/src/constants/sideMenu.ts
  frontend/src/contexts/AuthContext.tsx
  frontend/src/contexts/SubscriptionContext.tsx
  frontend/src/hooks/useChatSocket.ts
  frontend/src/hooks/useNotice.ts
  frontend/src/hooks/useSubscriptions.ts
  frontend/src/main.tsx
  frontend/src/pages/camps/community/CommunityPage.tsx
  frontend/src/pages/demo/api/ApiPage.tsx
  frontend/src/pages/demo/components/DemoPage.tsx
  frontend/src/pages/explore/ExplorePage.tsx
  frontend/src/pages/home/HomePage.tsx
  frontend/src/pages/search/SearchPage.tsx
  frontend/src/route/router.tsx
  frontend/src/type/api/chat.d.ts
  frontend/src/type/api/notice.d.ts
Labels: 🌝 FE, ✨ feature

#75 [BE] api 수정 및 버그 수정, 구독자 수 반환 추가
  backend/src/camp/camp.controller.ts
  backend/src/camp/camp.repository.ts
  backend/src/camp/camp.service.ts
  backend/src/camp/subscription.service.ts
  backend/src/http/camp.http
Labels: 🌚 BE, ✨ feature, 🐞 fix

#76 [BE] 모니터링 추가
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
Labels: 🌚 BE, ✨ feature

#78 [BE] api 수정
  backend/src/auth/auth.service.ts
  backend/src/camp/subscription.repository.ts
  backend/src/utils/logger.middleware.ts
Labels: 🌚 BE, 🐞 fix

#81 [FE, BE] 코멘트 삭제, 번역 기능 구현
  backend/package-lock.json
  backend/package.json
  backend/src/camp/camp.repository.ts
  backend/src/post/entities/post.entity.ts
  backend/src/post/entities/postTranslation.entity.ts
  backend/src/post/post.module.ts
  backend/src/post/post.repository.ts
  backend/src/post/post.service.ts
  backend/src/post/postTranslation.service.ts
  frontend/src/assets/icons/closeIcon.svg
  frontend/src/assets/icons/deleteIcon.svg
  frontend/src/components/button/LikeButton.tsx
  frontend/src/components/card/CommentCard.tsx
  frontend/src/components/card/PostConentCard.tsx
  frontend/src/components/chat/ChatBoxMessage.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/menu/ContentMenu.tsx
  frontend/src/components/menu/SideMenu.tsx
  frontend/src/components/menu/SubscribeMenuButton.tsx
  frontend/src/components/menu/SubscribedMenu.tsx
  frontend/src/components/profile/ProfileImage.tsx
  frontend/src/contexts/LanguageContext.tsx
  frontend/src/contexts/SubscriptionContext.tsx
  frontend/src/hooks/api/useCommentQuery.ts
  frontend/src/hooks/useLanguage.ts
  frontend/src/main.tsx
  frontend/src/pages/auth/signup/SignupForm.tsx
  frontend/src/pages/camps/CampInfo.tsx
  frontend/src/pages/camps/CampPage.tsx
  frontend/src/pages/camps/post/PostGrid.tsx
  frontend/src/pages/camps/post/PostModalLogic.tsx
  frontend/src/pages/camps/post/PostModalTemplate.tsx
  frontend/src/pages/explore/ExplorePage.tsx
  frontend/src/pages/explore/SearchInputTemplate.tsx
  frontend/src/pages/feed/FeedCardLogic.tsx
  frontend/src/pages/feed/FeedCardTemplate.tsx
  frontend/src/pages/subscriptions/SubscriptionsPage.tsx
  frontend/src/route/router.tsx
  frontend/src/type/api/api.d.ts
  frontend/src/type/api/comment.d.ts
  frontend/src/type/api/post.d.ts
Labels: 🌝 FE, 🌚 BE, ✨ feature

#85 [FE, BE] 버그 수정
  backend/src/camp/camp.service.ts
  backend/src/main.ts
  backend/src/post/post.service.ts
  backend/src/user/user.service.ts
  frontend/src/components/input/SearchInput.tsx
  frontend/src/components/menu/SideMenu.tsx
  frontend/src/components/slider/MediaSlider.tsx
  frontend/src/pages/camps/edit/CampProfileEditPage.tsx
  frontend/src/pages/camps/post/PostModalLogic.tsx
  frontend/src/pages/camps/post/PostModalTemplate.tsx
  frontend/src/pages/explore/SearchInputTemplate.tsx
  frontend/src/pages/feed/FeedCardLogic.tsx
  frontend/src/pages/feed/FeedCardTemplate.tsx
  frontend/src/pages/feed/FeedPage.tsx
  frontend/src/route/router.tsx
Labels: 🌝 FE, 🌚 BE, 🐞 fix

#88 [FE] 폰트 관련 버그 수정, 언어 설정 스타일 수정
  frontend/index.html
  frontend/src/assets/icons/campIcon.svg
  frontend/src/assets/icons/chatIcon.svg
  frontend/src/components/card/Card.tsx
  frontend/src/components/card/CommentCard.tsx
  frontend/src/components/chat/ChatBoxMessage.tsx
  frontend/src/components/menu/SideMenu.tsx
  frontend/src/components/menu/SideMenuButton.tsx
  frontend/src/components/menu/SubscribeMenuButton.tsx
  frontend/src/components/menu/SubscribedMenu.tsx
  frontend/src/components/radio/radio.tsx
  frontend/src/components/slider/MediaSlider.tsx
  frontend/src/components/ui/Text.tsx
  frontend/src/constants/sideMenu.tsx
  frontend/src/pages/camps/CampInfo.tsx
  frontend/src/pages/camps/edit/CampProfileEditPage.tsx
  frontend/src/pages/explore/ExplorePage.tsx
  frontend/src/pages/feed/FeedCardLogic.tsx
  frontend/src/pages/feed/FeedCardTemplate.tsx
  frontend/src/pages/feed/FeedPage.tsx
  frontend/src/styles/fonts.css
  frontend/tailwind.config.js
Labels: 🌝 FE, 🐞 fix

#89 [FE] 슬라이더, 캠프 정보 수정
  frontend/src/components/slider/MediaSlider.tsx
  frontend/src/pages/camps/CampInfo.tsx
  frontend/src/pages/camps/post/PostModalTemplate.tsx
  frontend/src/type/api/camp.d.ts
Labels: 🌝 FE, 🐞 fix

#92 [FE] ChatBox 원래대로 롤백
  frontend/src/components/chat/ChatBoxBody.tsx
  frontend/src/components/chat/ChatBoxBodyInfiniteMessages.tsx
  frontend/src/components/chat/ChatBoxBodySocketMessages.tsx
Labels: 🌝 FE, 🐞 fix

#93 [FE] 이미지 사이즈 최적화
  frontend/src/components/card/CommentCard.tsx
  frontend/src/components/card/PostCard.tsx
  frontend/src/components/card/PostConentCard.tsx
  frontend/src/components/chat/ChatBoxMessage.tsx
  frontend/src/components/slider/MediaSlider.tsx
  frontend/src/components/ui/Image.tsx
  frontend/src/pages/camps/CampInfo.tsx
  frontend/src/pages/explore/ExplorePage.tsx
  frontend/src/pages/explore/SearchInputTemplate.tsx
  frontend/src/pages/subscriptions/SubscriptionsPage.tsx
  frontend/src/utils/imageURL.ts
Labels: 🌝 FE, refactor

#95 [FE, BE] 코멘트 리렌더링 최적화, 썸네일 안보이는 버그 수정
  backend/src/image/image.service.ts
  backend/src/post/post.service.ts
  frontend/src/components/card/CommentCard.tsx
  frontend/src/hooks/api/useCommentQuery.ts
  frontend/src/pages/feed/FeedCardTemplate.tsx
  frontend/src/pages/search/SearchPage.tsx
  frontend/src/route/router.tsx
Labels: 🌝 FE, 🌚 BE, 🐞 fix

#96 [BE] 비디오 업로드 시 썸네일 안보이는 버그 수정
  backend/src/post/post.service.ts
Labels: 🌚 BE, 🐞 fix

#97 [BE]: 파일이 없을때 발생하는 버그 수정
  backend/src/post/post.service.ts
Labels: 🌚 BE, 🐞 fix

#98 [FE] 이미 지워진 이벤트를 다시 지우는 버그 수정
  frontend/src/pages/feed/FeedPage.tsx
Labels: 🌝 FE, 🐞 fix
